DB課題③ db-001〜005
ayktmr/quelcode-db pull request #5
Opened 2020-07-17 06:27 UTC by ayktmr

DB課題③ db-001〜005 の作成が完了しました。
レビューの程、宜しくお願い致します。

2020-07-19 10:20 UTC, ayktmr commented
DB課題③ db-006〜010 の作成が完了しました。
レビューの程、宜しくお願い致します。

2020-07-19 12:24 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-07-19 12:24 UTC, piasoratech commented on db/db-challenge3/db-010/db-010.sql
> +SELECT
このＳＱＬ文だと削除されている投稿が含まれてしまっているので修正をしましょう

2020-07-19 13:38 UTC, ayktmr commented on db/db-challenge3/db-010/db-010.sql
> +SELECT
修正致しました。
ご確認の程、お願い致します。

2020-07-20 23:53 UTC, choimake commented
LGTMです。次に進んでください。

2020-07-22 00:02 UTC, choimake reviewed
LGTMです。
参考までにコメントしたので、確認しておいてください。

2020-07-22 00:02 UTC, choimake commented on db/db-challenge3/db-012/db-012.sql
> +COMMIT;
（修正不要）`AND is_send = 1`の位置が気になります。
chatroom_users関連なのか、chotrooms関連なのかちょっと把握しにくかったので。

僕ならこう書きます。
```
BEGIN;
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
UPDATE
    chatrooms
SET
    is_send = 0,
    update_user_id = 1
WHERE
    is_deleted = 0
AND
    is_send = 1
AND
    (id NOT IN(
        SELECT DISTINCT chatroom_users_id
        FROM chatroom_users
        WHERE users_id = 1
        )
    );
COMMIT;
```

2020-07-22 00:02 UTC, choimake commented on db/db-challenge3/db-011/db-011.sql
> +    AND created_at <= '2020/04/26 11:30:00'
（修正不要）`BETWEEN`使っても書けますね。

2020-09-04 02:57 UTC, merged